In [5]:
import numpy as np
import math

def rotation():
    
    #First I took the position vectors values 'Xp, Yp, Zp'
    
    x = float(input("Please Enter 'Xp' Value: "))
    y = float(input("Please Enter 'Yp' Value: "))
    z = float(input("Please Enter 'Zp' Value: "))
    
    #I converted the given inputs to a 3x1 matrix (to get a better look)
    main_matrix = np.array([[x,y,z]])
    
    print("\nThe Position Vector You Entered Is Below\n",main_matrix,"\n--------------------------")
    
    #Then I converted 1x3 matris (to perform multiplication operations on the matrix)
    main_matrix = main_matrix.T
                            
    
    degree = int(input("\nPlease Enter The Rotation Angle In Degrees: "))

    axis = int(input("Please Enter The Rotation Axis: "))
    
    
    #Because the math library's cos and sin operations work in radians, I needed to convert the degrees to radians before processing them, thus I used the math.radian() function.
    
    matrix_rotation_one = np.array([[ 1, 0, 0],[ 0, math.cos(math.radians(degree)), math.sin(math.radians(degree))],[0,-math.sin(math.radians(degree)),math.cos(math.radians(degree))]])

    matrix_rotation_two = np.array([[ math.cos(math.radians(degree)), 0, -math.sin(math.radians(degree))],[ 0, 1, 0],[math.sin(math.radians(degree)),0,math.cos(math.radians(degree))]])

    matrix_rotation_three = np.array([[ math.cos(math.radians(degree)), math.sin(math.radians(degree)), 0],[ -math.sin(math.radians(degree)), math.cos(math.radians(degree)), 0],[0,0,1]])

    
    #I defined the operation using the necessary matrix for the provided rotation axes and displayed the new position vector and its coordinates.
    
    if axis == 1:
        print("\n##########################\n")
        a = matrix_rotation_one.dot(main_matrix)
        
        print("New Position Vector Of Point P:\nP ---> ",a.T)
        
        print("\nXp' --->", (a[0]))
        
        print("Yp' --->", (a[1]))
        
        print("Zp' --->", (a[2]))
        
        
    elif axis == 2:
        print("\n##########################\n")
        b = matrix_rotation_two.dot(main_matrix)
        
        print("New Position Vector Of Point P:\nP ---> ",b.T)
        
        print("\nXp' --->", (b[0]))
        
        print("Yp' --->", (b[1]))
        
        print("Zp' --->", (b[2]))
        
        
    elif axis == 3:
        print("\n##########################\n")
        c = matrix_rotation_three.dot(main_matrix)
        
        print("New Position Vector Of Point P:\nP ---> ",c.T)
        
        print("\nXp' --->", (c[0]))
        
        print("Yp' --->", (c[1]))
        
        print("Zp' --->", (c[2]))
        
    
    else:
        print("Axis Values Must Be '1, 2 or 3'.")
        
        

In [6]:
rotation()

Please Enter 'Xp' Value: 100
Please Enter 'Yp' Value: 120
Please Enter 'Zp' Value: 200

The Position Vector You Entered Is Below
 [[100. 120. 200.]] 
--------------------------

Please Enter The Rotation Angle In Degrees: -20
Please Enter The Rotation Axis: 2

##########################

New Position Vector Of Point P:
P --->  [[162.37329074 120.         153.73650982]]

Xp' ---> [162.37329074]
Yp' ---> [120.]
Zp' ---> [153.73650982]


In [7]:
rotation()

Please Enter 'Xp' Value: 162.37329074
Please Enter 'Yp' Value: 120
Please Enter 'Zp' Value: 153.73650982

The Position Vector You Entered Is Below
 [[162.37329074 120.         153.73650982]] 
--------------------------

Please Enter The Rotation Angle In Degrees: 25
Please Enter The Rotation Axis: 3

##########################

New Position Vector Of Point P:
P --->  [[197.87436921  40.13501656 153.73650982]]

Xp' ---> [197.87436921]
Yp' ---> [40.13501656]
Zp' ---> [153.73650982]


In [8]:
rotation()

Please Enter 'Xp' Value: 197.87436921
Please Enter 'Yp' Value: 40.13501656
Please Enter 'Zp' Value: 153.73650982

The Position Vector You Entered Is Below
 [[197.87436921  40.13501656 153.73650982]] 
--------------------------

Please Enter The Rotation Angle In Degrees: 7
Please Enter The Rotation Axis: 2

##########################

New Position Vector Of Point P:
P --->  [[177.66367616  40.13501656 176.70540064]]

Xp' ---> [177.66367616]
Yp' ---> [40.13501656]
Zp' ---> [176.70540064]
